apiVersion: v1
entries:
  my-hardhat:
  - apiVersion: v2
    appVersion: "1.0"
    created: "2024-12-31T17:26:56.781985+05:30"
    description: A Helm chart for Hardhat AI Pod and Service
    digest: f5a9b02e7cb5d6c79160530ebfce228951dc2cd2814c3f1a64dabb47e65c7914
    name: my-hardhat
    urls:
    - https://sathiyadev84.github.io/edgeai/my-hardhat-0.1.0.tgz
    version: 0.1.0
generated: "2024-12-31T17:26:56.781078+05:30"
